version: 2.1

jobs:
  test:
    docker:
      - image: cimg/ruby:3.1.0
    steps:
      - checkout
      - run:
          name: Bundle Install
          command: bundle install
      - run:
          name: Run Tests
          command: bundle exec rspec
      - store_artifacts:
          path: coverage

workflows:
  version: 2
  workflow:
    jobs:
      - test